### ISSUE TITLE
Rails auth

### ISSUE THREAD

**Issue by w1zeman1p** [Amit-P-Amin/rationalreadsproposal#4]
I'd probably keep all authentication in multiple rails pages, rather than making those backbone.

**Comment by Amit-P-Amin** [comment]
Why's that? Is there an advantage to keeping authentication to rails? Doesn't that violate the single-page app pattern?

**Comment by w1zeman1p** [comment]
The apps don't need to be pure single page. More of a hybrid is fine. Auth is such a simple and mundane piece of the puzzle it's a good thing to take a shortcut on. Doing auth fully single page is extra and unnecesary work. But if you want to add that as a bling feature of your project go for it.

**Comment by Amit-P-Amin** [comment]
Great, I will do that then.
